- .github/pull_request_template.md
- heroku-app-create/heroku-app-create.py
[PT-#164666252](https://www.pivotaltracker.com/story/show/164666252)
Do not kick off a deploy after any app has already been spawned. Heroku Review Apps Beta deploys automatically when the PR gets a push (GitHub integration).
Also do not redeploy to Related Apps - let them stay static. If anyone needs to modify those, don't trample their changes.
Grant permissions to the apps that were spawned. Detection of specific permissions groups wasn't possible, so we had to do very wide grants. If we do not do this, then only the automation account has access to deploy/operate these apps.
Remove some redundant messaging in the PR conversation flow.
These are usability enhancements in order to make things less confusing and the behavior more predictable. The permissions change was essential for …
> [164666252] review envs enhancements

- heroku-app-create/heroku-app-create.py
[PT-#165223041](https://www.pivotaltracker.com/story/show/165223041)
Grants `view` and `manage` privileges on Heroku Apps in the Review Environments setup, instead of `view`, `deploy` and `operate`.
This method will require users who want to operate on these apps to grant themselves permissions to manipulate the apps individually. However, it will prevent the entire team from being spammed when things like release-phase commands fail.
Tested by spinning up a new review environment and checking the granted permissions.
cc/ @fbjork @ozeias @rajkhatri
> [165223041] grant manage privileges instead of view/deploy/operate to avoid spam

- heroku-app-create/heroku-app-create.py
[PT-#165772055](https://www.pivotaltracker.com/story/show/165772055)
URL encode the branch names when requesting from GitHub API
fixes review envs when using URL encoded branches
Use an URL encoded branch name
cc/ @rkapuria
> [165772055] deal with urlencoding branch names

- heroku-app-create/heroku-app-create.py
[PT-#166830335](https://www.pivotaltracker.com/story/show/166830335)
cc/
> [166830335] don't let Heroku spin down your apps if the post-deploy fails

- heroku-app-create/README.md
- heroku-app-create/heroku-app-create.py
[PT-#1234](https://www.pivotaltracker.com/story/show/1234)
In order to require the `review-env` label, set the environment variable `REQUIRE_LABEL` to `true`.
In the general and most developer-friendly use case, we feel that these should spin up automatically when a PR is opened.
cc/
> optional use of labels to restrict action

- heroku-app-create/README.md
- heroku-app-create/heroku-app-create.py
[PT-#1234](https://www.pivotaltracker.com/story/show/1234)
cc/
> [166571899] fix KeyError

- heroku-app-create/heroku-app-create.py
[PT-#166830335](https://www.pivotaltracker.com/story/show/166830335)
Submit the same flag to stop it from reaping review apps that fail deployment
This is not good behavior for our purposes b/c we can't go in and find the error messages. And it also leads to downstream undesirable effects (respawn of apps that have no permissions :( :( :( ).
The option is at least accepted without error. And our test app that failed release phase still exists now.
cc/
> [166830335] stop reaping on review apps as well

- heroku-app-create/heroku-app-create.py
[PT-#167046147](https://www.pivotaltracker.com/story/show/167046147)
Use a more direct way to pull na app by it's name.
Simplifies the code and fixes a bug where the apps weren't being properly found before respawning.
Tested using an affected branch.
cc/
> [167046147] simpler way to get an app by name

- heroku-app-create/heroku-app-create.py
[PT-#167046147](https://www.pivotaltracker.com/story/show/167046147)
forgot to update the check
The failure actually comes back with an 'id' attribute, so keep it.
cc/
> [167046147] name already taken

- heroku-app-destroy/Dockerfile
- heroku-app-destroy/README.md
- heroku-app-destroy/heroku-app-destroy.py
[PT-#167079139](https://www.pivotaltracker.com/story/show/116707913934)
New action for the cleanup of Heroku apps in Review Environments.
GitHub changed the way that actions are executed when a PR is closed, requiring the use of a filter in order to avoid abrupt cancellation of the running workflow.
Tested by creating and destroying a review env
cc/
> [167079139] proper cleanup

- heroku-app-create/heroku-app-create.py
[PT-#167079644](https://www.pivotaltracker.com/story/show/167079644)
cc/
> [167079644] user grants incomplete - support pagination

- heroku-app-create/heroku-app-create.py
[PT-#1234](https://www.pivotaltracker.com/story/show/1234)
cc/
> print some information that would be helpful in debugging

- okta-whitelist-url-create/Dockerfile
- okta-whitelist-url-create/README.md
- okta-whitelist-url-create/okta-whitelist-url-create.py
- okta-whitelist-url-destroy/Dockerfile
- okta-whitelist-url-destroy/README.md
- okta-whitelist-url-destroy/okta-whitelist-url-destroy.py
[PT-#167155556](https://www.pivotaltracker.com/story/show/167155556)
Creates two new actions for the review env scripts, one to whitelist the Okta login URI for the `web` portion of the review environment, and one to remove it from the whitelist. 
People are going to want to test RBAC related features, which is entirely controlled by membership in Okta groups. In order to login with .ninja accounts, using Okta, to a review environment and get the appropriate access token, the login URI has to be whitelisted with the Okta sandbox. These PRs (the `heroku-review-envs` one and the 4 workflow updates from `real-server`, `api`, `api-gateway`, and `website`) will allow that to happen. 
- Testing instructions will be updated shortly
- [ x ] New feature _(a non-breaking change which adds …
> [#167155556] Create GitHub script to automatically whitelist review environment URLs upon creation, and remove on tear down

- heroku-addon-create/heroku-addon-create.py
- heroku-app-create/heroku-app-create.py
- okta-whitelist-url-create/okta-whitelist-url-create.py
- okta-whitelist-url-destroy/okta-whitelist-url-destroy.py
[PT-#166335632](https://www.pivotaltracker.com/story/show/166335632)
Use the event payload for information about the PR. This should be used only on `pull_request` events, so that input is expected.
We want to catch some exceptions instead of letting it error out and abort the GitHub action. Also catch a few exceptions to be more informative in case of issues.
Fetching the PR info using another call to GitHub API is time consuming and can produce errors. Use what we have already.
When the action aborts altogether, it could result in incorrect app names and missing permissions.
Tested via multiple PRs of Actions V2 and a PR for the old HCL format.
This is compatible with both HCL and YAML based GitHub Actions workflows.
cc/
> [166335632] use event payload and better error handling

- heroku-app-create/heroku-app-create.py
[PT-#168843927](https://www.pivotaltracker.com/story/show/168843927)
Outputs an error message and continues when grants fail.
People are experiencing issues where they aren't granted access. Debug.
cc/
> [168843927] debugging info on access grants

- heroku-addon-create/Dockerfile
- heroku-app-create/Dockerfile
- heroku-app-destroy/Dockerfile
- okta-whitelist-url-create/Dockerfile
- okta-whitelist-url-destroy/Dockerfile
- python-action/Dockerfile
[PT-#168940260](https://www.pivotaltracker.com/story/show/168940260)
Build off a common docker image in order to speed up the build process, as github actions does not cache.
Brings the container build time down from 2m10s to about 25s.
GitHub Actions does not cache docker builds, so we incur additional wait time for our automations. Build an intermediate image, host on dockerhub, and pull from that instead.
Tested on some internal PRs.
cc/
> [#168940260] add intermediate image

- heroku-addon-create/heroku-addon-create.py
[PT-#165354551](https://www.pivotaltracker.com/story/show/165354551)
Allow more specific configuration of the apps to which to attach the addons. We may attach the addons to related apps only, depending on the situation.
We need to support behavior where the addons aren't always associated with the origin app. The origin app can be any app. but the apps associate with an addon are specific.
tested on all new PRs for the new inventory service addition to review environments.
cc/
> [165354551] modifications for inventory service shared redis

- heroku-app-create/heroku-app-create.py
Quick fix to avoid errors on a particular type of error we're running into now.
Currently breaks some review envs consistently.
cc/
> better null detection

- heroku-addon-create/heroku-addon-create.py
… than the addon structure (e.g. error messages)
[PT-#169304805](https://www.pivotaltracker.com/story/show/169304805)
The heroku API responses when requesting a list of existing addon attachments for an app can have various structures / types. Ensure that when looking for an addon name we first check the type and move on if it's not an addon structure.
heroku-addon-create.py throws an error and bails out if heroku responds with any structure other than the addon structure. We want to continue processing and ignore other structures in this scenario.
[This](https://github.com/TheRealReal/real-server/pull/16442/checks?check_run_id=270397718) is an examplle:
cc/
> [169304805] type checking for addon responses

- heroku-addon-create/heroku-addon-create.py
- heroku-app-create/heroku-app-create.py
- heroku-app-destroy/heroku-app-destroy.py
- heroku-config-var-set/heroku-config-var-set.py
- okta-whitelist-url-create/okta-whitelist-url-create.py
- okta-whitelist-url-destroy/okta-whitelist-url-destroy.py
https://www.pivotaltracker.com/story/show/171890684
Changes to heroku-app-config and heorku-addon-create to allow use of env variables intead of args
Will allow for a single workflow file for all repos.
Tested review env creation with api repo.
cc/
> [171890684] review env configure workflow variables

- heroku-app-create/heroku-app-create.py
[PT-#173233664](https://www.pivotaltracker.com/story/show/173233664)
Grant `operate` and `deploy` to all users.
- Saves time manually going into UI or CLI and granting permissions.
- Why not?
cc/
> [#173233664] Updated permissions

- heroku-app-create/heroku-app-create.py
[PT-#173948593](https://www.pivotaltracker.com/story/show/173948593)
Uses an unpublished API to adjust the boot timeout for review apps.
Bootup times have been increasing with each new consumer that we add. This has cause quite a few issues when starting applications because they may exceed the default 60 sec timeout.
cc/
> [#173948593] Auto bump timeout

- heroku-slack-alert/Dockerfile
- heroku-slack-alert/entrypoint.sh
[PT-#176598769](https://www.pivotaltracker.com/story/show/1234)
This Dockerfile helps github actions to send alert when the review-env app creation fails.
cc/
> #176598769 Adding slack alert Dockerfile for heroku review-app creation failure notifications
